apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: go-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-component
    app.kubernetes.io/part-of: test-app-167088069
  name: go-component
  namespace: 8nx2kk7q
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: go-component
status:
  loadBalancer: {}
