apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  annotations:
    build.appstudio.openshift.io/application: test-app-167088069
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/component: go
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: go
  namespace: 8nx2kk7q
spec:
  git_provider:
    secret:
      key: github.token
      name: pipelines-as-code-secret
    webhook_secret:
      key: https___github.com_devfile-samples_devfile-sample-go-basic
      name: pipelines-as-code-webhooks-secret
  url: https://github.com/devfile-samples/devfile-sample-go-basic.git
