apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go
    app.kubernetes.io/part-of: test-app-167088069
  name: go
  namespace: 8nx2kk7q
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: go
    weight: 100
status: {}
